/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ConnectDB;
import DAO.khachHangDAO;
import DAO.loaiKHDAO;
import POJO.khachHang;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import POJO.loaiKH;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import model.hoTro;

/**
 *
 * @author Duong Duy
 */
public class quanLyCTKMKH extends javax.swing.JFrame {

    /**
     * Creates new form quanLyCTKMKH
     */
    String tentk = "";
    ArrayList<loaiKH> dsLoaiKH;
    DefaultTableModel modelTBKH;
    Vector titleKH = new Vector();
    ArrayList<khachHang> dsKH;
    DefaultTreeModel modelTree;
    DefaultMutableTreeNode root = null;

    public quanLyCTKMKH(String tentk) {
        this.tentk = tentk;
        initComponents();
        setLocationRelativeTo(null);
        txtMaloai.requestFocus();
        titleKH.add("Mã khách hàng");
        titleKH.add("Tên khách hàng");
        titleKH.add("Giới tính");
        titleKH.add("Địa chỉ");
        titleKH.add("SDT");
        titleKH.add("Tên loại khách hàng");

        modelTBKH = new DefaultTableModel();
        modelTBKH.setColumnIdentifiers(titleKH);
        tbKhachHang.setModel(modelTBKH);
        root = (DefaultMutableTreeNode) treeLoaiKH.getModel().getRoot();
        modelTree = (DefaultTreeModel) treeLoaiKH.getModel();
        treeLoaiKH.setModel(modelTree);
        loadDataLoaiKH();

        loadDataKH();
        treeLoaiKH.expandRow(0);
    }

    void loadDataKH() {
        modelTBKH.setRowCount(0);
        dsKH = khachHangDAO.getdsKH();
        for (khachHang kh : dsKH) {
            Vector r = new Vector();
            r.add(kh.getMakh());
            r.add(kh.getTenKh());
            r.add(kh.getGioiTinh());
            r.add(kh.getDiaChi());
            r.add(kh.getSdt());
            r.add(loaiKHDAO.timLoaiKH(kh.getMaLoaiKH()).getTenLoaiKH());
            modelTBKH.addRow(r);
        }
    }

    void xoaTrangLKH() {
        txtMaloai.setEditable(true);
        txtMaloai.setText("");
        txtMaloai.requestFocus();
        txtGiamGia.setText("");
        txtTenLoai.setText("");
        btnThem.setEnabled(true);
    }

    void loadDataLoaiKH() {
        cbbTenLoaiKH.removeAllItems();
        while (root.getChildCount() != 0) {
            root.remove(root.getChildCount() - 1);
        }
        dsLoaiKH = loaiKHDAO.getdsLoaiKH();
        for (loaiKH lkh : dsLoaiKH) {
            cbbTenLoaiKH.addItem(lkh.getTenLoaiKH());
            DefaultMutableTreeNode parent = new DefaultMutableTreeNode(lkh);
            root.add(parent);
        }
        modelTree.reload(root);
        for (int i = 0; i < treeLoaiKH.getRowCount(); i++) {
            treeLoaiKH.expandRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src//img//nen2.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        }
        ;
        jLabel13 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbbTenLoaiKH = new javax.swing.JComboBox<>();
        btnThemKH = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnSuaKH = new javax.swing.JButton();
        btnLamMoiKH = new javax.swing.JButton();
        btnDongKH = new javax.swing.JButton();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        lbTenKH = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbGiamGia = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        lbTenLoai = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaloai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeLoaiKH = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình khuyến mãi cho khách hàng");
        setResizable(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mã khách hàng");

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtTenKH.setName("Tên khách hàng"); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tên khách hàng:");

        txtMa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMa.setName("Mã khách hàng"); // NOI18N
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Giới tính");

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtDiaChi.setName("Địa chỉ"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Số điện thoại");

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSDT.setName("Số điện thoại"); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tên loại khách hàng:");

        cbbTenLoaiKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        btnThemKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnThemKH.setText("Thêm");
        btnThemKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        btnXoaKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnXoaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnXoaKH.setText("Xoá");
        btnXoaKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        btnSuaKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSuaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hammer.png"))); // NOI18N
        btnSuaKH.setText("Sửa");
        btnSuaKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKHActionPerformed(evt);
            }
        });

        btnLamMoiKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLamMoiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnLamMoiKH.setText("Làm mới");
        btnLamMoiKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiKHActionPerformed(evt);
            }
        });

        btnDongKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnDongKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnDongKH.setText("Đóng");
        btnDongKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDongKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongKHActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNam);
        rdNam.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rdNam.setForeground(new java.awt.Color(51, 255, 204));
        rdNam.setSelected(true);
        rdNam.setText("Nam");
        rdNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(rdNu);
        rdNu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rdNu.setForeground(new java.awt.Color(255, 51, 255));
        rdNu.setText("Nữ");
        rdNu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbTenKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbTenKH.setForeground(new java.awt.Color(255, 51, 51));
        lbTenKH.setText("...");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Mã khách hàng:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Tên loại khách hàng:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Tên khách hàng:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Giảm giá");

        lbGiamGia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbGiamGia.setForeground(new java.awt.Color(255, 51, 51));
        lbGiamGia.setText("...");

        lbMa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbMa.setForeground(new java.awt.Color(255, 51, 51));
        lbMa.setText("...");

        lbTenLoai.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbTenLoai.setForeground(new java.awt.Color(255, 51, 51));
        lbTenLoai.setText("...");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Địa chỉ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 204));
        jLabel7.setText("Thông tin khuyến mãi");

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbKhachHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseReleased(evt);
            }
        });
        tbKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbKhachHangKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhachHang);

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hammer.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Mã loại");

        txtMaloai.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMaloai.setName("Mã loại khách hàng"); // NOI18N

        txtTenLoai.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtTenLoai.setName("Tên loại"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Tên loại");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Giảm giá");

        txtGiamGia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtGiamGia.setName("Giảm giá"); // NOI18N
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyTyped(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Danh sách loại khách hàng");
        treeLoaiKH.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeLoaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                treeLoaiKHMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(treeLoaiKH);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLamMoi)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThemKH)
                                .addGap(102, 102, 102)
                                .addComponent(btnLamMoiKH)
                                .addGap(88, 88, 88)
                                .addComponent(btnXoaKH)
                                .addGap(93, 93, 93)
                                .addComponent(btnSuaKH)
                                .addGap(87, 87, 87)
                                .addComponent(btnDongKH))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdNam)
                                        .addGap(35, 35, 35)
                                        .addComponent(rdNu))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbTenLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbMa)
                                                    .addComponent(lbTenKH)
                                                    .addComponent(lbTenLoai)
                                                    .addComponent(lbGiamGia)))
                                            .addComponent(jLabel7)))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoi, btnSua, btnThem, btnXoa});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel5, jLabel8, jLabel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel15, jLabel17, jLabel18, jLabel6});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbTenLoaiKH, txtDiaChi, txtMa, txtSDT, txtTenKH});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDongKH, btnLamMoiKH, btnSuaKH, btnThemKH, btnXoaKH});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnLamMoi))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(rdNam)
                            .addComponent(rdNu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbbTenLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMa)
                        .addGap(18, 18, 18)
                        .addComponent(lbTenKH)
                        .addGap(18, 18, 18)
                        .addComponent(lbTenLoai)
                        .addGap(18, 18, 18)
                        .addComponent(lbGiamGia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDongKH)
                        .addComponent(btnSuaKH))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThemKH)
                        .addComponent(btnLamMoiKH)
                        .addComponent(btnXoaKH)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        xoaTrangLKH();
        xoaTrangKH();
        loadDataKH();
        loadDataLoaiKH();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (hoTro.ktraRong(txtMaloai) || hoTro.ktraRong(txtTenLoai) || hoTro.ktraRong(txtGiamGia)) {
            return;
        }
        String maLoai = txtMaloai.getText().trim();
        String tenLoai = txtTenLoai.getText().trim();
        if (JOptionPane.showConfirmDialog(null, "Bạn muốn thêm loại " + tenLoai + " ?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            float giamGia = Float.parseFloat(txtGiamGia.getText().trim());
            int i = loaiKHDAO.themLoaiKH(maLoai, tenLoai, giamGia);
            if (i != -1) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", 1);
                xoaTrangLKH();
                loadDataLoaiKH();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:      
        if (treeLoaiKH.getSelectionPath() != null) {
            DefaultMutableTreeNode selectNode = (DefaultMutableTreeNode) treeLoaiKH.getLastSelectedPathComponent();
            if (selectNode.getUserObject() instanceof loaiKH) {
                if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá loại " + txtTenLoai.getText().trim() + " ?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                    int i = loaiKHDAO.xoaLoaiKH(txtMaloai.getText());
                    if (i != -1) {
                        JOptionPane.showMessageDialog(null, "Đã xoá", "Thông báo", 1);
                        loadDataLoaiKH();
                        loadDataKH();
                        xoaTrangLKH();
                        xoaTrangKH();
                    }
                }
            } else {
                if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá tất cả loại khách hàng?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                    loaiKHDAO.xoaLoaiKH();
                    loadDataKH();
                    loadDataLoaiKH();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mời bạn chọn loại khách hàng để xoá", "Thông báo", 1);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:       
        if (treeLoaiKH.getSelectionPath() != null) {
            if (hoTro.ktraRong(txtTenLoai) || hoTro.ktraRong(txtGiamGia)) {
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn sửa loại khách hàng này?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                int i = loaiKHDAO.suaLoaiKH(txtMaloai.getText(), txtTenLoai.getText().trim(), Float.parseFloat(txtGiamGia.getText().trim()));
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đã sửa", "Thông báo", 1);
                    loadDataLoaiKH();
                    loadDataKH();
                    xoaTrangLKH();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mời bạn chọn loại khách hàng để sửa", "Thông báo", 1);
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
        if (hoTro.ktraRong(txtMa) || hoTro.ktraRong(txtTenKH) || hoTro.ktraRong(txtDiaChi) || hoTro.ktraRong(txtSDT)) {
            return;
        }
        if (!hoTro.ktraSDT(txtSDT)) {
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "Bạn muốn thêm khách hàng " + txtTenKH.getText().trim() + "?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            String gt = "Nam";
            if (rdNu.isSelected()) {
                gt = "Nữ";
            }

            int i = khachHangDAO.themKH(txtMa.getText().trim(), txtTenKH.getText().trim(), gt, txtDiaChi.getText().trim(), txtSDT.getText().trim(), loaiKHDAO.timLoaiKH(cbbTenLoaiKH.getSelectedItem().toString()).getMaLoaiKH());
            if (i != -1) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", 1);
                loadDataKH();
                xoaTrangKH();
                loadDataLoaiKH();
                xoaTrangLKH();
            }
        }
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        // TODO add your handling code here:
        int row = tbKhachHang.getSelectedRow();
        if (row >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá khách hàng " + txtTenKH.getText().trim() + "?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {

                int i = khachHangDAO.xoaKH(txtMa.getText());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đã xoá", "Thông báo", 1);
                    loadDataKH();
                    xoaTrangKH();
                    loadDataLoaiKH();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng để xoá!!", "Thông báo", 1);
        }
    }//GEN-LAST:event_btnXoaKHActionPerformed
    void viewKH(String maLoai, String maKH) {
        txtMa.setEditable(false);
        khachHang kh = khachHangDAO.layTTKH(maLoai, maKH);
        lbMa.setText(kh.getMakh());
        txtMa.setText(kh.getMakh());
        txtTenKH.setText(kh.getTenKh());
        if (kh.getGioiTinh().toLowerCase().equals("nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
        txtDiaChi.setText(kh.getDiaChi());
        txtSDT.setText(kh.getSdt());
        lbTenKH.setText(kh.getTenKh());
        lbTenLoai.setText(loaiKHDAO.timLoaiKH(kh.getMaLoaiKH()).getTenLoaiKH());
        lbGiamGia.setText(loaiKHDAO.timLoaiKH(kh.getMaLoaiKH()).getGiamGia() + "");
        cbbTenLoaiKH.setSelectedItem(loaiKHDAO.timLoaiKH(kh.getMaLoaiKH()).getTenLoaiKH().trim());
        btnThemKH.setEnabled(false);
    }
    private void tbKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMousePressed
        // TODO add your handling code here:
        int row = tbKhachHang.getSelectedRow();
        if (row >= 0) {
            viewKH(loaiKHDAO.timLoaiKH(modelTBKH.getValueAt(row, 5).toString()).getMaLoaiKH(), modelTBKH.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_tbKhachHangMousePressed

    private void btnLamMoiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiKHActionPerformed
        // TODO add your handling code here:
        xoaTrangKH();
        tbKhachHang.setSelectionMode(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnLamMoiKHActionPerformed

    private void txtSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSDTKeyTyped

    private void btnSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKHActionPerformed
        // TODO add your handling code here:
        int row = tbKhachHang.getSelectedRow();
        if (row >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn thêm khách hàng " + txtTenKH.getText().trim() + "?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {

                String gt = "Nam";
                if (rdNu.isSelected()) {
                    gt = "Nữ";
                }
                int i = khachHangDAO.suaKH(txtMa.getText(), txtTenKH.getText().trim(), gt, txtDiaChi.getText().trim(), txtSDT.getText().trim(), loaiKHDAO.timLoaiKH(cbbTenLoaiKH.getSelectedItem().toString()).getMaLoaiKH());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đã sửa", "Thông báo", 1);
                    loadDataKH();
                    xoaTrangKH();
                    loadDataLoaiKH();

                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng để sửa!!", "Thông báo", 1);
        }
    }//GEN-LAST:event_btnSuaKHActionPerformed

    private void btnDongKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongKHActionPerformed
        // TODO add your handling code here:
        new quanly(tentk).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDongKHActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void treeLoaiKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeLoaiKHMousePressed
        // TODO add your handling code here:

        if (root.getChildCount() == 0 || treeLoaiKH.getSelectionPath() == null) {
            return;
        }
        DefaultMutableTreeNode selecNode = (DefaultMutableTreeNode) treeLoaiKH.getLastSelectedPathComponent();
        if (selecNode == root) {
            xoaTrangKH();
            xoaTrangLKH();
            loadDataKH();
            return;
        }
        Object selectObject = selecNode.getUserObject();
        if (selectObject instanceof loaiKH) {
            txtMaloai.setText(((loaiKH) selectObject).getMaLoaiKH());
            txtTenLoai.setText(((loaiKH) selectObject).getTenLoaiKH());
            txtGiamGia.setText(((loaiKH) selectObject).getGiamGia() + "");
            btnThem.setEnabled(false);
            txtMaloai.setEditable(false);
            modelTBKH.setRowCount(0);
            for (khachHang kh : khachHangDAO.layTTKH(((loaiKH) selectObject).getMaLoaiKH())) {
                Vector r = new Vector();
                r.add(kh.getMakh());
                r.add(kh.getTenKh());
                r.add(kh.getGioiTinh());
                r.add(kh.getDiaChi());
                r.add(kh.getSdt());
                r.add(kh.getMaLoaiKH());
                modelTBKH.addRow(r);
                xoaTrangKH();
            }
        }

    }//GEN-LAST:event_treeLoaiKHMousePressed

    private void tbKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKhachHangKeyReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(tbKhachHang);
    }//GEN-LAST:event_tbKhachHangKeyReleased

    private void tbKhachHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(tbKhachHang);

    }//GEN-LAST:event_tbKhachHangMouseReleased

    private void txtGiamGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGiamGiaKeyTyped
    void xoaTrangKH() {
        txtMa.setEditable(true);
        lbGiamGia.setText("");
        lbMa.setText("");
        lbTenKH.setText("");
        lbTenLoai.setText("");
        txtMa.requestFocus();
        txtMa.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtTenKH.setText("");
        cbbTenLoaiKH.setSelectedIndex(0);
        rdNam.setSelected(true);
        btnThemKH.setEnabled(true);
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongKH;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiKH;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaKH;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbTenLoaiKH;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbGiamGia;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTenLoai;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTree treeLoaiKH;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaloai;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
