/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ConnectDB;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.hoTro;

/**
 *
 * @author Duong Duy
 */
public class quanLyDoanhThu extends javax.swing.JFrame {

    /**
     * Creates new form quanLyDoanhThu
     */
    Vector title = new Vector();
    DefaultTableModel modelTB;
    String tentk = "";

    public quanLyDoanhThu(String tentk) {
        initComponents();
        this.tentk = tentk;
        setResizable(false);
        setLocationRelativeTo(null);
        modelTB = new DefaultTableModel();
        title.add("Mã nước");
        title.add("Tên nước");
        title.add("Đơn giá");
        title.add("Tổng số lượng");
        title.add("Tổng thành tiền");
        modelTB.setColumnIdentifiers(title);
        jTable1.setModel(modelTB);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src//img//nen6.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnNuocBanNhieu = new javax.swing.JButton();
        btnTKDTTheoNgay = new javax.swing.JButton();
        txtNgayLap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNVLapNhieuHD = new javax.swing.JButton();
        txtDoanhThu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaThongTin = new javax.swing.JTextArea();
        btnLamMoi = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý doanh thu");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Các nước uống được bán ra");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnNuocBanNhieu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNuocBanNhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market_analysis.png"))); // NOI18N
        btnNuocBanNhieu.setText("Nước uống được bán nhiều nhất");
        btnNuocBanNhieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuocBanNhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuocBanNhieuActionPerformed(evt);
            }
        });

        btnTKDTTheoNgay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnTKDTTheoNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market_analysis.png"))); // NOI18N
        btnTKDTTheoNgay.setText("Thống kê doanh thu ngày");
        btnTKDTTheoNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTKDTTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKDTTheoNgayActionPerformed(evt);
            }
        });

        txtNgayLap.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtNgayLap.setName("Ngày lập "); // NOI18N
        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Nhập ngày lập:");

        btnNVLapNhieuHD.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNVLapNhieuHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market_analysis.png"))); // NOI18N
        btnNVLapNhieuHD.setText("Nhân viên lập hoá đơn nhiều nhất");
        btnNVLapNhieuHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNVLapNhieuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVLapNhieuHDActionPerformed(evt);
            }
        });

        txtDoanhThu.setEditable(false);
        txtDoanhThu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Doanh thu:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Thông tin");

        txaThongTin.setEditable(false);
        txaThongTin.setColumns(20);
        txaThongTin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txaThongTin.setLineWrap(true);
        txaThongTin.setRows(5);
        txaThongTin.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaThongTin);

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnDong.setText("ĐÓNG");
        btnDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLamMoi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnTKDTTheoNgay)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDong)
                            .addComponent(btnNVLapNhieuHD))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnNuocBanNhieu)
                    .addGap(651, 651, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNVLapNhieuHD, btnNuocBanNhieu});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnTKDTTheoNgay)
                    .addComponent(jLabel4)
                    .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNVLapNhieuHD)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnDong))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnNuocBanNhieu)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void loadData() {
        modelTB.setRowCount(0);
        String sql = "select CHITIETHD.MANUOCUONG,TENNUOCUONG,CHITIETHD.DONGIA ,SUM(soluong) 'TSL',SUM(THANHTIEN) 'TTT' from CHITIETHD,NuocUong where CHITIETHD.MANUOCUONG=NUOCUONG.MANUOCUONG group by CHITIETHD.MANUOCUONG,TENNUOCUONG,CHITIETHD.DONGIA";
        try {
            ConnectDB.getConnection();
            ResultSet rs = ConnectDB.executeQuery(sql);
            while (rs.next()) {
                Vector r = new Vector();
                r.add(rs.getString("MANUOCUONG").trim());
                r.add(rs.getString("TENNUOCUONG").trim());
                r.add(rs.getFloat("DONGIA"));
                r.add(rs.getInt("TSL"));
                r.add(rs.getFloat("TTT"));
                modelTB.addRow(r);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi", "Thông báo", 1);
        }
        ConnectDB.close();
    }
    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLapActionPerformed

    private void btnNuocBanNhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuocBanNhieuActionPerformed
        // TODO add your handling code here:
        String sql = "{call nuocUongBanNhieuNhat}";
        modelTB.setRowCount(0);
        try {
            ConnectDB.getConnection();
            CallableStatement cstm = ConnectDB.getCon().prepareCall(sql);
            ResultSet rs = cstm.executeQuery();

            while (rs.next()) {

                Vector r = new Vector();
                r.add(rs.getString("MANUOCUONG").trim());
                r.add(rs.getString("TENNUOCUONG").trim());
                r.add(rs.getFloat("DONGIA"));
                r.add(rs.getInt("TSL"));
                r.add(rs.getFloat("TTT"));
                modelTB.addRow(r);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi thủ tục", "Thông báo", 1);
        }
        ConnectDB.close();
    }//GEN-LAST:event_btnNuocBanNhieuActionPerformed
    void xoaTrang() {
        txtDoanhThu.setText("");
        txtNgayLap.setText("");
        txtNgayLap.requestFocus();
        txaThongTin.setText("");
        loadData();
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        xoaTrang();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTKDTTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKDTTheoNgayActionPerformed
        // TODO add your handling code here:
        if (!hoTro.ktraNgay(txtNgayLap)) {
            return;
        }
        String sql = "set dateformat dmy; select sum(thanhToan) from HOADON where NGAYRAHD='" + txtNgayLap.getText().trim() + "'";
        try {
            ConnectDB.getConnection();
            ResultSet rs = ConnectDB.executeQuery(sql);
            if (rs.next()) {
                txtDoanhThu.setText("" + rs.getFloat(1));
            }
            txtNgayLap.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi doanh thu", "Thông báo", 1);
        }
        ConnectDB.close();
    }//GEN-LAST:event_btnTKDTTheoNgayActionPerformed

    private void btnNVLapNhieuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVLapNhieuHDActionPerformed
        // TODO add your handling code here:
        String sql = "select TENNV,SL from nhanvien nv,(select Manv,count(*) 'SL' from HOADON group by MANV having count(*)>=all(select count(*) from HOADON group by MANV)) tk where tk.MANV=nv.MANV";
        try {
            ConnectDB.getConnection();
            ResultSet rs = ConnectDB.executeQuery(sql);
            String s = "";
            while (rs.next()) {
                s += "Tên nhân viên:" + rs.getString("tennv") + "-Số hoá đơn đã lập:" + rs.getInt("SL") + "\n";
            }
            s.substring(0, s.length() - 1);
            txaThongTin.setText(s);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi", "Thông báo", 1);
        }
        ConnectDB.close();
    }//GEN-LAST:event_btnNVLapNhieuHDActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        new quanly(tentk).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(jTable1);
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(jTable1);

    }//GEN-LAST:event_jTable1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNVLapNhieuHD;
    private javax.swing.JButton btnNuocBanNhieu;
    private javax.swing.JButton btnTKDTTheoNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txaThongTin;
    private javax.swing.JTextField txtDoanhThu;
    private javax.swing.JTextField txtNgayLap;
    // End of variables declaration//GEN-END:variables
}
