/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.banDAO;
import DAO.chiTietHDDAO;
import DAO.hoaDonDAO;
import DAO.khachHangDAO;
import DAO.nhanVienDAO;
import DAO.nuocUongDAO;
import POJO.ban;
import POJO.nuocUong;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.hoTro;

/**
 *
 * @author HP
 */
public class thanhtoan extends javax.swing.JFrame {

    /**
     * Creates new form thanhtoan
     */
    DefaultTableModel modelTbNuocUong;
    DefaultTableModel modelTbBan;
    Vector dsMonTungBan;
    String maNV = "";
    int rowBan = -1;

    public thanhtoan(String manv) {
        initComponents();
        maNV = manv;
        setLocationRelativeTo(null);
        hoTro.clock(lbTime);
        txtTenNV.setText(nhanVienDAO.timTenNVTheoMa(manv));
        setResizable(false);
        modelTbNuocUong = (DefaultTableModel) tbNuocUong.getModel();
        modelTbBan = (DefaultTableModel) tbBan.getModel();
        loadTT();
    }

    void loadTT() {
        banDAO.updateTinhTrang();
        dsMonTungBan = new Vector();
        for (nuocUong n : nuocUongDAO.getdsNuocUong()) {
            cbbTenNuoc.addItem(n.getTenNuoc());
        }
        for (ban b : banDAO.getdsban()) {
            cbbBan.addItem(b.getTenBan());
        }
        String tinhTrang;
        modelTbBan.setRowCount(0);
        for (ban b : banDAO.getdsban()) {
            tinhTrang = "Trống";
            if (b.getTinhTrang() == 1) {
                tinhTrang = "Có người";
            }
            Vector r = new Vector();
            r.add(b.getMaBan());
            r.add(b.getTenBan());
            r.add(tinhTrang);
            modelTbBan.addRow(r);
            dsMonTungBan.add(new Vector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlDoiMatKhau = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src//img//nenmk.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtNhapLaiMK = new javax.swing.JPasswordField();
        btnQuayLai = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNuocUong = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src//img//Hinhnen-Coffee-4.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel2 = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTongCong1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        spnSoLuong = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        cbbTenNuoc = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbGiamGia = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbLoaiKH = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBan = new javax.swing.JTable();
        btnXoa1 = new javax.swing.JButton();
        cbbBan = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        dlDoiMatKhau.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlDoiMatKhau.setTitle("Đổi mật khẩu");
        dlDoiMatKhau.setBackground(new java.awt.Color(0, 102, 102));
        dlDoiMatKhau.setMinimumSize(new java.awt.Dimension(563, 400));
        dlDoiMatKhau.setSize(new java.awt.Dimension(470, 390));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 51));
        jLabel13.setText("Đổi mật khẩu");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel17.setText("Mật khẩu cũ:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setText("Mật khẩu mới");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel19.setText("Nhập lại mật khẩu:");

        btnXacNhan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input_validation.png"))); // NOI18N
        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        txtMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMatKhau.setName("Mật khẩu cũ"); // NOI18N

        txtMatKhauMoi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMatKhauMoi.setName("Mật khẩu mới"); // NOI18N

        txtNhapLaiMK.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtNhapLaiMK.setName("Nhập lại mật khẩu"); // NOI18N

        btnQuayLai.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuayLai)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel13))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnQuayLai, btnXacNhan});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayLai)
                    .addComponent(btnXacNhan))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addGap(40, 40, 40)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout dlDoiMatKhauLayout = new javax.swing.GroupLayout(dlDoiMatKhau.getContentPane());
        dlDoiMatKhau.getContentPane().setLayout(dlDoiMatKhauLayout);
        dlDoiMatKhauLayout.setHorizontalGroup(
            dlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlDoiMatKhauLayout.setVerticalGroup(
            dlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanh toán");

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        lbTime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 51, 153));

        tbNuocUong.setBackground(new java.awt.Color(204, 204, 204));
        tbNuocUong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbNuocUong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbNuocUong.setForeground(new java.awt.Color(255, 255, 255));
        tbNuocUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nước", "Tên Nước", "Đơn giá (VNĐ)", "Số lượng (ly)", "Thành Tiền (VNĐ)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNuocUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbNuocUongMouseReleased(evt);
            }
        });
        tbNuocUong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbNuocUongKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbNuocUong);

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTime)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(lbTime)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tổng cộng:");

        txtTongCong.setEditable(false);
        txtTongCong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giảm giá");

        txtGiamGia.setEditable(false);
        txtGiamGia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("%");

        txtTongCong1.setEditable(false);
        txtTongCong1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thành tiền:");

        txtThanhTien.setEditable(false);
        txtThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtThanhTien.setName("Thành tiền"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tiền khách đưa:");

        txtTienKhachDua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTienKhachDua.setName("Tiền khách đưa"); // NOI18N
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tiền thừa:");

        txtTienThua.setEditable(false);
        txtTienThua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã Hóa Đơn:");

        txtMaHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMaHD.setName("Mã hoá đơn"); // NOI18N
        txtMaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaHDKeyReleased(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deposit.png"))); // NOI18N
        btnLuu.setText("Thanh toán & In");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Số lượng:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên nước:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tên nhân viên:");

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        spnSoLuong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Nhập mã khuyến mãi:");

        txtMaKM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMaKM.setName("Mã khuyễn mãi"); // NOI18N
        txtMaKM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaKMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaKMKeyTyped(evt);
            }
        });

        cbbTenNuoc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbbTenNuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbbTenNuocKeyTyped(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 153, 153));
        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setToolTipText("");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên khách hàng:");

        lbTenKH.setBackground(new java.awt.Color(255, 51, 51));
        lbTenKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTenKH.setForeground(new java.awt.Color(51, 255, 255));
        lbTenKH.setText("...");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Giảm giá");

        lbGiamGia.setBackground(new java.awt.Color(255, 51, 51));
        lbGiamGia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbGiamGia.setForeground(new java.awt.Color(51, 255, 255));
        lbGiamGia.setText("...");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Loại khách hàng:");

        lbLoaiKH.setBackground(new java.awt.Color(255, 51, 51));
        lbLoaiKH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbLoaiKH.setForeground(new java.awt.Color(0, 255, 255));
        lbLoaiKH.setText("...");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Thông tin khuyến mãi");

        lbThongBao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThongBao.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTongCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnLuu))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbTenNuoc, 0, 270, Short.MAX_VALUE)
                            .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(lbTenKH)
                                    .addComponent(lbGiamGia)
                                    .addComponent(lbLoaiKH)))
                            .addComponent(jLabel15))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel14, jLabel16});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLuu, btnThem});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtTongCong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnLuu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cbbTenNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lbTenKH))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(lbGiamGia)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(lbLoaiKH))))))
                .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(457, 457, 457))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLuu, btnThem});

        tbBan.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tbBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Tên bàn", "Tình trạng"
            }
        ));
        tbBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbBanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbBanMouseReleased(evt);
            }
        });
        tbBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbBanKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbBan);

        btnXoa1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXoa1.setText("Chuyển bàn");
        btnXoa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        cbbBan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(1348, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 169, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXoa1)
                .addGap(18, 18, 18)
                .addComponent(cbbBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        jMenu1.setText("Tài khoản");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key.png"))); // NOI18N
        jMenuItem1.setText("Đổi mật khẩu");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jMenuItem2.setText("Đóng");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTenNuocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbTenNuocKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTenNuocKeyTyped
    void themNuoc(int row) {
        boolean checkMon = true;
        banDAO.updateTinhTrang(tbBan.getValueAt(row, 0).toString().trim(), true);
        String tenNuoc = cbbTenNuoc.getSelectedItem().toString();
        int soLuong = Integer.parseInt(spnSoLuong.getValue().toString());
        for (int i = 0; i < modelTbNuocUong.getRowCount(); i++) {
            if (modelTbNuocUong.getValueAt(i, 1).toString().equals(tenNuoc)) {
                int soluongbd = Integer.parseInt(modelTbNuocUong.getValueAt(i, 3).toString());
                soluongbd += soLuong;
                modelTbNuocUong.setValueAt(soluongbd, i, 3);
                modelTbNuocUong.setValueAt(soluongbd * Float.parseFloat(modelTbNuocUong.getValueAt(i, 2).toString()), i, 4);
                checkMon = false;
                break;
            }
        }
        if (checkMon) {
            Vector r = nuocUongDAO.timTenNuocHD(tenNuoc, soLuong);
            modelTbNuocUong.addRow(r);
        }
        ((Vector) dsMonTungBan.get(row)).clear();
        for (int i = 0; i < modelTbNuocUong.getRowCount(); i++) {
            Vector r = new Vector();
            r.add(modelTbNuocUong.getValueAt(i, 0));
            r.add(modelTbNuocUong.getValueAt(i, 1));
            r.add(modelTbNuocUong.getValueAt(i, 2));
            r.add(modelTbNuocUong.getValueAt(i, 3));
            r.add(modelTbNuocUong.getValueAt(i, 4));
            ((Vector) dsMonTungBan.get(row)).add(r);
        }
        modelTbBan.setValueAt("Có người", row, 2);
    }

    void tinhTien() {
        float sum = 0;
        for (int i = 0; i < modelTbNuocUong.getRowCount(); i++) {
            sum += Float.parseFloat(modelTbNuocUong.getValueAt(i, 4).toString());
        }
        txtTongCong.setText("" + sum);
        float tienGiam = 0;

        if (!txtGiamGia.getText().equals("")) {
            txtTongCong1.setText(txtTongCong.getText());
            float giamGia = (Float.parseFloat(txtGiamGia.getText()));
            tienGiam = sum * giamGia / (float) 100;
        }
        txtThanhTien.setText("" + (sum - tienGiam));
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        rowBan = tbBan.getSelectedRow();
        if (rowBan < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn", "Thông báo", 2);
            return;
        }
        System.out.println(rowBan);
        themNuoc(rowBan);
        tinhTien();
        tinhTienKhach();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtMaKMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKMKeyReleased
        // TODO add your handling code here:
        try {
            ResultSet rs = khachHangDAO.timTTKH(txtMaKM.getText().trim());
            if (rs.next()) {
                lbTenKH.setText(rs.getString("tenkh"));
                lbLoaiKH.setText(rs.getString("tenloaikh"));
                lbGiamGia.setText("" + rs.getFloat("giamgia"));
                txtGiamGia.setText(lbGiamGia.getText());
                txtTongCong1.setText(txtTongCong.getText());
                tinhTien();
                tinhTienKhach();
            } else {
                txtGiamGia.setText("");
                txtTongCong1.setText("");
                lbTenKH.setText("...");
                lbLoaiKH.setText("...");
                lbGiamGia.setText("...");
                tinhTien();
                tinhTienKhach();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtMaKMKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbNuocUong.getSelectedRow();
        rowBan = tbBan.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào để xoá", "Thông báo", 1);
            return;
        }

        if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá nước " + tbNuocUong.getValueAt(row, 1) + "?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            modelTbNuocUong.removeRow(row);
            if (tbNuocUong.getRowCount() == 0) {
                banDAO.updateTinhTrang(tbBan.getValueAt(rowBan, 0).toString().trim(), false);
                modelTbBan.setValueAt("Trống", rowBan, 2);
            }
            ((Vector) dsMonTungBan.get(rowBan)).remove(row);
            tinhTien();
            tinhTienKhach();
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTienKhachDuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTienKhachDuaKeyTyped

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        rowBan = tbBan.getSelectedRow();
        int rowCount = tbNuocUong.getRowCount();
        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null, "Hoá đơn rỗng không cần thanh toán", "Thông báo", 1);
            return;
        }
        if (hoTro.ktraRong(txtTienKhachDua)) {
            return;
        }
        String ktr = "HD\\d{2,}";
        if (!txtMaHD.getText().toUpperCase().matches(ktr)) {
            JOptionPane.showMessageDialog(null, "Hoá đơn có dạng hdxx", "Thông báo", 1);
            txtMaHD.requestFocus();
            return;
        }

        float tienDua = Float.parseFloat(txtTienKhachDua.getText());

        float tienTraLai = tienDua - Float.parseFloat(txtThanhTien.getText());
        if (tienTraLai < 0) {
            JOptionPane.showMessageDialog(null, "Khách đưa không đủ tiền", "Thông báo", 1);
            txtTienKhachDua.requestFocus();
            return;
        }

        if (JOptionPane.showConfirmDialog(null, "Bạn muốn thanh toán hoá đơn " + txtMaHD.getText().trim(), "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            txtTienThua.setText("" + tienTraLai);
            String mahd = txtMaHD.getText();
            float thanhToan = Float.parseFloat(txtThanhTien.getText());
            float giamGia = 0;
            if (!txtGiamGia.getText().equals("")) {
                giamGia = Float.parseFloat(txtGiamGia.getText().trim());
            }

            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            String noiDungFile = "Mã hoá đơn:" + mahd + "\tNgày lập:" + df.format(Calendar.getInstance().getTime()) + "\nTên nhân viên:" + txtTenNV.getText() + "\n" + banDAO.layTenBanTheoMa(tbBan.getValueAt(rowBan, 0).toString()) + "\n=========================================================================================================\n" + "Tên nước\t\tSố lượng\t\tĐơn giá\t\tThành tiền\n";
            int j = hoaDonDAO.insert(mahd, thanhToan, maNV, giamGia, tbBan.getValueAt(rowBan, 0).toString());
            if (j != -1) {
                for (int i = 0; i < rowCount; i++) {
                    chiTietHDDAO.insert(mahd, modelTbNuocUong.getValueAt(i, 0).toString(), Integer.parseInt(modelTbNuocUong.getValueAt(i, 3).toString()), Float.parseFloat(modelTbNuocUong.getValueAt(i, 2).toString()), Float.parseFloat(modelTbNuocUong.getValueAt(i, 4).toString()));
                    noiDungFile += modelTbNuocUong.getValueAt(i, 1).toString() + "\t\t" + modelTbNuocUong.getValueAt(i, 3).toString() + "\t\t\t" + modelTbNuocUong.getValueAt(i, 2).toString() + "\t\t" + modelTbNuocUong.getValueAt(i, 4).toString() + "\n";
                }
                noiDungFile += "=========================================================================================================\n\t\t\t\t\t\t\tTổng cộng:" + txtTongCong.getText() + "\n\t\t\t\t\t\t\tGiảm giá:" + giamGia + "%" + "\n\t\t\t\t\t\t\tThành tiền:" + txtThanhTien.getText() + "\n\t\t\t\t\t\t\tTiền khách đưa:" + txtTienKhachDua.getText() + "\n\t\t\t\t\t\t\tTiền thừa:" + txtTienThua.getText();
                createNew();
                j = hoTro.writeFile(mahd, noiDungFile);
                if (j != -1) {
                    banDAO.updateTinhTrang(tbBan.getValueAt(rowBan, 0).toString().trim(), false);
                    modelTbBan.setValueAt("Trống", rowBan, 2);
                    ((Vector) dsMonTungBan.get(rowBan)).clear();
                    JOptionPane.showMessageDialog(null, "Thanh toán thành công", "Thông báo", 1);
                    hoTro.openFile(mahd);
                }
            }
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    void createNew() {
        spnSoLuong.setValue(1);
        txtGiamGia.setText("");
        txtMaHD.setText("");
        txtMaKM.setText("");
        txtThanhTien.setText("");
        txtTienKhachDua.setText("");
        txtTienThua.setText("");
        txtTongCong.setText("");
        txtTongCong1.setText("");
        lbGiamGia.setText("...");
        lbLoaiKH.setText("...");
        lbTenKH.setText("...");
        modelTbNuocUong.setRowCount(0);
        cbbTenNuoc.setSelectedIndex(0);
        lbThongBao.setText("");
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        dlDoiMatKhau.setLocationRelativeTo(null);
        dlDoiMatKhau.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new nhanVien(maNV).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (hoTro.ktraRong(txtMatKhau) || hoTro.ktraRong(txtMatKhauMoi) || hoTro.ktraRong(txtNhapLaiMK)) {
            return;
        }
        if (nhanVienDAO.timMKTheoMa(maNV).equals(hoTro.md5(txtMatKhau.getText().trim()))) {
            if (txtMatKhauMoi.getText().equals(txtNhapLaiMK.getText())) {
                int i = nhanVienDAO.doiMatKhau(maNV, hoTro.md5(txtMatKhauMoi.getText().trim()));
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Thông báo", 1);
                    dlDoiMatKhau.dispose();
                    setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu không giống nhau", "Thông báo", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mật khẩu không chính xác", "Thông báo", 1);
        }

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        dlDoiMatKhau.dispose();
        setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed
    void tinhTienKhach() {
        try {
            float conLai = Float.parseFloat(txtTienKhachDua.getText().trim()) - Float.parseFloat(txtThanhTien.getText());
            if (conLai < 0) {
                lbThongBao.setText("Khách đưa không đủ tiền");
                txtTienThua.setText("");
            } else {
                lbThongBao.setText("");
                txtTienThua.setText("" + conLai);
            }
        } catch (Exception e) {
        }
    }
    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        tinhTienKhach();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void txtMaKMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKMKeyTyped

    private void txtMaHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaHDKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMaHDKeyReleased

    private void tbBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBanMousePressed
        // TODO add your handling code here:
        rowBan = tbBan.getSelectedRow();

        if (rowBan >= 0) {
            modelTbNuocUong.setRowCount(0);
            Vector dsMon = (Vector) dsMonTungBan.get(rowBan);

            for (int i = 0; i < dsMon.size(); i++) {
                Vector r = (Vector) dsMon.get(i);
                modelTbNuocUong.addRow(r);
            }
            txtMaKM.setText("");
            txtMaKMKeyReleased(null);
            tinhTien();
            tinhTienKhach();

        }
    }//GEN-LAST:event_tbBanMousePressed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        rowBan = tbBan.getSelectedRow();
        int index = cbbBan.getSelectedIndex();
        if (rowBan < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bàn", "Thông báo", 1);
            return;
        }
        int tinhTrang = banDAO.layTinhTrangTheoMa(tbBan.getValueAt(rowBan, 0).toString());
        if (tinhTrang == 0) {
            JOptionPane.showMessageDialog(null, tbBan.getValueAt(rowBan, 1) + " Chưa có người ở bàn này!!!!!", "Thông báo", 1);
            return;
        }
        if (rowBan == index) {
            JOptionPane.showMessageDialog(null, "Bạn đang ở " + tbBan.getValueAt(rowBan, 1).toString().toLowerCase() + " rồi nên không thể chuyển!!!!!", "Thông báo", 1);
            return;
        }
        tinhTrang = banDAO.layTinhTrangTheoMa(tbBan.getValueAt(index, 0).toString());
        if (tinhTrang == 1) {
            JOptionPane.showMessageDialog(null, tbBan.getValueAt(index, 1) + " này đã có người!!!", "Thông báo", 1);
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "Bạn muốn chuyển từ " + modelTbBan.getValueAt(rowBan, 1).toString() + " sang " + modelTbBan.getValueAt(index, 1).toString(), "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            dsMonTungBan.set(index, ((Vector) dsMonTungBan.get(rowBan)));
            modelTbNuocUong.setRowCount(0);
            dsMonTungBan.set(rowBan, new Vector());

            banDAO.updateTinhTrang(tbBan.getValueAt(index, 0).toString(), true);
            banDAO.updateTinhTrang(tbBan.getValueAt(rowBan, 0).toString(), false);
            JOptionPane.showMessageDialog(null, "Chuyển bàn thành công", "Thông báo", 1);
            tbBan.setValueAt("Trống", rowBan, 2);
            tbBan.setValueAt("Có người", index, 2);
            tbBanMousePressed(null);
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void tbBanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBanMouseReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(tbBan);
    }//GEN-LAST:event_tbBanMouseReleased

    private void tbNuocUongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNuocUongMouseReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(tbNuocUong);
    }//GEN-LAST:event_tbNuocUongMouseReleased

    private void tbNuocUongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNuocUongKeyReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(tbNuocUong);

    }//GEN-LAST:event_tbNuocUongKeyReleased

    private void tbBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbBanKeyReleased
        // TODO add your handling code here:
        hoTro.offEdittingTable(tbBan);
    }//GEN-LAST:event_tbBanKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> cbbBan;
    private javax.swing.JComboBox<String> cbbTenNuoc;
    private javax.swing.JDialog dlDoiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbGiamGia;
    private javax.swing.JLabel lbLoaiKH;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbTime;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTable tbBan;
    private javax.swing.JTable tbNuocUong;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMK;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongCong;
    private javax.swing.JTextField txtTongCong1;
    // End of variables declaration//GEN-END:variables
}
